"""Transparent configurable guardrails for deterministic insights."""

MIN_STATE_ORDERS = 100
MIN_SELLER_ORDERS = 20
MIN_CATEGORY_REVIEWS = 25
MIN_RELATIONSHIP_REVIEWS = 100
MIN_RFM_STATE_CUSTOMERS = 25

MEANINGFUL_PERCENT_CHANGE = 2.0
WARNING_RATE_POINT_CHANGE = 1.0
CRITICAL_RATE_POINT_CHANGE = 3.0
MEANINGFUL_SCORE_CHANGE = 0.10
MEANINGFUL_DAY_CHANGE = 0.50

EXECUTIVE_LIMIT = 6
PAGE_LIMIT = 5
